### PR TITLE
Doge 350

### PR DESCRIPTION
**Pull request by Sesshoumaru404**
**Link back to Jira ticket:**

## Description
While checking for to see if it works on python 3, decided you added an csv option 

## Implementation
./contact_methods.py -k <api_key> -f test.csv

### Steps to test changes
* Add the -f flag and a filename

## Documentation 
- [] There is documentation that needs to be updated upon merging these changes

Links to any documentation to be updated:

### CODE REVIEW

**Comment by shonin** [comment]
I think this needs to have master merged into it.

**Comment by ethanmsl** [comment]
@Sesshoumaru404 
Brought up to speed with master.
Please see this Merge PR (already accepted) for description: [Update: Master to Branch Merge](https://github.com/PagerDuty/public-support-scripts/pull/103), including a link to one file who's changes are worth noting (the root `.gitignore`)

**Comment by Sesshoumaru404** [comment]
Tested and works as expected

**Review by ethanmsl — APPROVED** [review]
Approved, based on past and recent testing by rykener & Sessh

**Pull request merged**
