### PR TITLE
docs(overrides_bulk_operations): added input key(s) for files

### PR DESCRIPTION
**Pull request by ethanmsl**
Improved documentation would be ideal, however in the context of coming refactors and documentation changes this seems adequate

**Link back to Jira ticket:**

### Steps to test changes
*

## Documentation 
- [x] There is documentation that needs to be updated upon merging these changes

Links to any documentation to be updated:

### CODE REVIEW

**Comment by DanJeffs** [comment]
Do the dates have to be in a specific format at all?

**Review by shirleyilenechan — COMMENTED** [review]
I think I think the schedules parameter on line 40 could be improved, because it is a bit ambiguous what it means by "all schedules" here: it could refer to "all schedules" across the customer's PD account, or "all schedules" which include the vacationer. 

Also, I think that "More columns can be included after the first" could be clarified as well. It's not super clear which columns can be included - what do those additional columns refer to? how many additional columns can be added? what does the script do to those columns?

**Comment by ethanmsl** [comment]
re: [slack thread](https://pagerduty.slack.com/archives/G9M91RT2A/p1693960313091059?thread_ts=1693956751.357199&cid=G9M91RT2A)

Yeah, those are all very valid issues.
The repo needs to be reworked.  No one actually knows what everything does at the moment.  We’re just migrating the existing information about the flags to the readme to give people a place to start.
That whole repo needs to be … not burned to the ground and rebuilt necessarily, but significantly reworked.
This was a part of an initiative months ago to go from nothing to something at all.  So we’d still like to get the current changes merged — as it’s not obvious that deep sift to de-obfuscate the repo is going to happen in the nearterm.

([this is the current state of that repo](https://github.com/PagerDuty/public-support-scripts/tree/master/overrides_bulk_operations))


Right now we’re working on really improving the quality of newly released scripts:
e.g. [this one](https://github.com/PagerDuty/public-support-scripts/tree/master/custom_field) now has more extensive user docs, tester docs, logging, testing, in-code documentation, and very easy to follow design.
(as well as options for secure and convenient api key passing) 

The effort to rework old scripts isn’t much lower than the effort to just add new ones of higher quality, so we’re leaning toward the latter as our default.  Jumping on any requests or potential security issues as they come.
I do have plans to go through and dockerize a lot of the old scripts though — so they’ll at least be frozen and won’t continue risking sub-dependency rot.
(where dependencies of dependencies of … change in ways that propagate up to the main scripts — as python and ruby classically do not track sub-deps so you can’t lock to them)

Right now, besides assiting with new public and internal scripts I'm working through years of stale PRs.
So having _something_ here while we deobfuscate would be a plus. :)

**Comment by ethanmsl** [comment]
(Oh, also note this [issue filed at time of PR](https://github.com/PagerDuty/public-support-scripts/issues/87).  This is a stopgap measure with need for a fix formally filed.)

**Comment by ethanmsl** [comment]
In the interest of fostering the current productive skepticisim wrt stop-gap measures I'm going to close this PR.

An issue concerning need for a proper fix was filed at the time of the PR and is still alive[issue filed at time of PR](https://github.com/PagerDuty/public-support-scripts/issues/87).  It also contains the flag information in this PR.

Honestly, I'm just as happy not to put my name on a well-calculated, but uninspiring PR like this. :) 
So thanks ;)

**Pull request closed without merging**
